# Generated by Django 3.2.23 on 2024-02-13 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_auto_20240211_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_cs', to=settings.AUTH_USER_MODEL, verbose_name='CS'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
