# Generated by Django 3.2.23 on 2024-02-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_auto_20240213_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpdatesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_update', to='customers.customer', verbose_name='Object')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=200, verbose_name='UUID')),
                ('start_date', models.DateTimeField(verbose_name='Start Subscription Date')),
                ('end_date', models.DateTimeField(verbose_name='End Subscription Date')),
                ('price', models.IntegerField(verbose_name='Subscription Price')),
                ('collected_price', models.IntegerField(verbose_name='Collected Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_customer', to='customers.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('note', models.CharField(default=uuid.uuid4, max_length=600, verbose_name='Note')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_note', to='customers.subscription', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionUpdatesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_update', to='customers.subscription', verbose_name='Object')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.DeleteModel(
            name='UpdatesRecord',
        ),
    ]
