# Generated by Django 3.2.23 on 2024-02-13 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_auto_20240213_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cs',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cs', to=settings.AUTH_USER_MODEL, verbose_name='CS'),
        ),
    ]
