# Generated by Django 3.2.23 on 2024-02-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20240227_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deuration',
            field=models.CharField(blank=True, max_length=200, verbose_name='Deuration'),
        ),
    ]
